# This is a basic workflow that is manually triggered
on:
  push:
    branches: [ "dev" ]

name: Testing
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  testing:
    # The type of runner that the job will run on
    name: testing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # Runs a single command using the runners shell
    - name: General testing
      run: sudo -S ./test.sh
